on: [ workflow_dispatch, push ]
permissions:
  id-token: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::107018555615:role/github
          aws-region: us-east-1
      - run: aws sts get-caller-identity