name: test
on: [ workflow_dispatch, push ]
env:
  TF_INPUT: false
  TF_IN_AUTOMATION: true
permissions:
  id-token: write
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::107018555615:role/github
          aws-region: us-east-1
      - run: terraform init
      - run: terraform validate
      - run: terraform apply -auto-approve
      - run: terraform plan -detailed-exitcode
      - run: terraform destroy -auto-approve
      - run: terraform plan -detailed-exitcode -destroy
      - run: terraform fmt -check
